# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f1eab5a92345172e91040d5ec27f6c1984974491a14a925f42f143f35843e6ddb25e5bf108999ef686d019a01002a3d4433ea98304fe289331cebb5c45f9a535

test:
  secret_key_base: 11d87cb339e5131b51731b20f3478f02e7a474e7ca03f1e6d3f577839484af3af9f7c376fa7b078b587f2fe8aba4e970dab76bc2523f2619f98bf7cec7649970

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
